### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by trofort** [EgorPetkevich/NoteMeProject#1]
Этот файл должен быть в папке со стилями

https://github.com/EgorPetkevich/NoteMeProject/blob/ded8c398e8f0e34de06e557d720ccadd759eb846/NoteMe/Resourse/Consts/UILabel%2BConsts.swift#L10-L41

**Comment by trofort** [comment]
Этот тоже

https://github.com/EgorPetkevich/NoteMeProject/blob/ded8c398e8f0e34de06e557d720ccadd759eb846/NoteMe/Resourse/Consts/UIView%2BConsts.swift#L10-L31

**Comment by EgorPetkevich** [comment]
исправил
