### ISSUE TITLE
InfoView

### ISSUE THREAD

**Issue by trofort** [EgorPetkevich/NoteMeProject#2]
Лучше привязать инфоВью в центр, а татл верхний привязать к топу инфоВью

https://github.com/EgorPetkevich/NoteMeProject/blob/ded8c398e8f0e34de06e557d720ccadd759eb846/NoteMe/Modules/Auth/SingIn/SingInVC.swift#L77-L86

**Comment by EgorPetkevich** [comment]
Привязал infoView по центру оси Y. Вопрос: на всех экранах так сделать? Получатся, что мы не соблюдаем расстояние между  logoImage и TitleLabel, или я не так сделал?

**Comment by trofort** [comment]
Там приоритетнее чтобы вью по вертикальному центру а не расстояние до лого

**Comment by trofort** [comment]
Исправь на всех экранах

**Comment by EgorPetkevich** [comment]
done
